defaults:
  - callbacks
  - _self_
hydra:
  run:
    dir: './experiments/'
paths:
  data: ${hydra:runtime.cwd}/data
  log: ${hydra:run.dir}
files:
  test_data: ${paths.data}/t10k-images-idx3-ubyte.gz
  test_labels: ${paths.data}/t10k-labels-idx1-ubyte.gz
  train_data: ${paths.data}/train-images-idx3-ubyte.gz
  train_labels: ${paths.data}/train-labels-idx1-ubyte.gz
params:
  epochs: 3
  lr: 5.0e-05
  batch_size: 128



