defaults:
  - _self_
  - files: dataset1
  - callbacks
  - optimizer: sgd
hydra:
  run:
    dir: './experiments/'
paths:
  data: ${hydra:runtime.cwd}/data
  log: ${hydra:run.dir}
# files: dataset1
params:
  epochs: 3
  lr: 5.0e-05
  batch_size: 128



