paths:
  data: ${hydra:runtime.cwd}/in-progress/data
  log: ${hydra:runtime.cwd}/in-progress/runs

files:
  test_data: ${paths.data}/t10k-images-idx3-ubyte.gz
  test_labels: ${paths.data}/t10k-labels-idx1-ubyte.gz
  train_data: ${paths.data}/train-images-idx3-ubyte.gz
  train_labels: ${paths.data}/train-labels-idx1-ubyte.gz


params:
  epochs: 20
  lr: 5e-5
  batch_size: 128